# The order of module is very important, precedence from top to bottom.
imports:
  - path: github.com/hbstack/pagination
  - path: github.com/hbstack/bs-tooltip
  - path: github.com/hugomods/google-analytics
  - path: github.com/hbstack/theme-cards

  - path: github.com/hbstack/google-fonts
  - path: github.com/hbstack/bootstrap
  - path: github.com/hbstack/mermaid
  - path: github.com/hugomods/katex
  - path: github.com/hugomods/shortcodes
  - path: github.com/hugomods/images
  - path: github.com/hbstack/code-block-panel
  - path: github.com/hbstack/syntax-highlighting/styles/gruvbox
  - path: github.com/hbstack/noscript
  - path: github.com/hbstack/progress-bar
  - path: github.com/hbstack/pwa

  # icons modules
  # - path: github.com/hugomods/icons/vendors/font-awesome
  # - path: github.com/hugomods/icons/vendors/feather
  - path: github.com/hugomods/icons/vendors/lucide

  - path: github.com/hbstack/back-to-top
  - path: github.com/hbstack/bigger-picture
  - path: github.com/hbstack/bs-tooltip

  - path: github.com/hbstack/header
  - path: github.com/hbstack/header/modules/socials
  - path: github.com/hbstack/header/modules/search
  - path: github.com/hbstack/header/modules/theme-toggle
  - path: github.com/hbstack/header/modules/news

  - path: github.com/hbstack/blog/modules/sidebar/profile
  - path: github.com/hbstack/blog/modules/sidebar/posts
  - path: github.com/hbstack/blog/modules/sidebar/taxonomies
  - path: github.com/hbstack/blog
  - path: github.com/hbstack/blog/modules/breadcrumb
  - path: github.com/hbstack/blog/modules/featured-image
  - path: github.com/hbstack/blog/modules/toc-scrollspy
  - path: github.com/hbstack/blog/modules/heading-sign
  - path: github.com/hbstack/blog/modules/post-nav
  - path: github.com/hbstack/blog/modules/related-posts
  - path: github.com/hbstack/blog/modules/giscus

  - path: github.com/hbstack/docs
  - path: github.com/hbstack/docs/modules/breadcrumb
  - path: github.com/hbstack/docs/modules/featured-image
  - path: github.com/hbstack/docs/modules/toc-scrollspy
  - path: github.com/hbstack/docs/modules/heading-sign
  - path: github.com/hbstack/docs/modules/doc-nav
  - path: github.com/hbstack/docs/modules/giscus

  - path: github.com/hbstack/footer
  - path: github.com/hbstack/footer/modules/socials

  - path: github.com/hugomods/seo/modules/base
  - path: github.com/hugomods/seo/modules/alternatives
  - path: github.com/hugomods/seo/modules/favicons
  - path: github.com/hugomods/seo/modules/open-graph
  - path: github.com/hugomods/seo/modules/schema
  - path: github.com/hugomods/seo/modules/translations
