[build]
command = """
curl -LJO https://github.com/sass/dart-sass/releases/download/${DART_SASS_VERSION}/dart-sass-${DART_SASS_VERSION}-linux-x64.tar.gz && \
tar -xf dart-sass-${DART_SASS_VERSION}-linux-x64.tar.gz && \
rm dart-sass-${DART_SASS_VERSION}-linux-x64.tar.gz && \
export PATH=/opt/build/repo/dart-sass:$PATH && \
npm ci && \
hugo --minify --gc -b $URL
"""
publish = "public"

[build.environment]
NODE_VERSION = "22"
HUGO_VERSION = "0.145.0"
DART_SASS_VERSION = "1.85.1"